#:kivy 1.7.2

<HomeScreen>:
	    
    TextInput: 
    	text: "funny stuff"
        background_color: .8, .8, 0, 1
        size_hint: .5, .1
        multiline: True
		pos_hint: {'x': .25, 'y': .45}
		font_size: 24
		padding: 12
		
    Button:
    	text: "Translate"
    	pos_hint: {'x': .4, 'y': .35}
    	size_hint: .2, .08
    	font_size: 10    

    Label: 
    	text: "*Bedouin مُخْتَبَر*"
    	font_size: 30
    	pos_hint: {'x': .3, 'y': .75}
    	size_hint: .4, .2
        
    
